<?xml version="1.0" encoding="utf-8"?>

<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <TypeScriptCompileBlocked>true</TypeScriptCompileBlocked>
    <Authors>Rainer Erismann</Authors>
    <Company>Rainer Erismann</Company>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
  </PropertyGroup>

  <PropertyGroup>
    <!-- Nuget semantic, like <Version>0.16.1-pre2</Version> -->
    <Version>1.0.0-pre1</Version>

    <!-- File versioning, like <Version>0.16.1</Version> -->
    <FileVersion>1.0.0</FileVersion>
    <AssemblyVersion>1.0.0</AssemblyVersion>
  </PropertyGroup>

  <PropertyGroup>
    <!-- Include symbol files (*.pdb) in the built .nupkg -->
    <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
  </PropertyGroup>

</Project>